name: docker-latest arch

on:
  push:
    branches: test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_target: [ 'x86_64:linux/amd64', 'arm:linux/arm64,linux/arm/v7,linux/arm/v8']
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: docker buildx ${{ matrix.docker_target }}
      run: |
        DOCKER_FILE=$(echo "${{ matrix.docker_target }}" | cut -f1 -d:)/Dockerfile
        DOCKER_IMAGE=myImageName:latest
        DOCKER_PLATFORM=$(echo "${{ matrix.docker_target }}" | cut -f2 -d:)
        docker buildx build . --no-cache --platform ${DOCKER_PLATFORM} -t "${DOCKER_IMAGE}" -f "${DOCKER_FILE}" --push
